ALTER TABLE triage_logs ADD COLUMN IF NOT EXISTS latency_ms DOUBLE PRECISION;
ALTER TABLE triage_logs ADD COLUMN IF NOT EXISTS retry_count INTEGER DEFAULT 0;
ALTER TABLE triage_logs ADD COLUMN IF NOT EXISTS had_retry BOOLEAN DEFAULT FALSE;
ALTER TABLE triage_logs ADD COLUMN IF NOT EXISTS error_type VARCHAR(100);