ALTER TABLE triage_logs
ADD COLUMN IF NOT EXISTS approval_required boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS approval_status varchar(30) NOT NULL DEFAULT 'not_required',
ADD COLUMN IF NOT EXISTS approval_reason text NULL,
ADD COLUMN IF NOT EXISTS approved_by varchar(120) NULL,
ADD COLUMN IF NOT EXISTS approved_at timestamptz NULL,
ADD COLUMN IF NOT EXISTS rejected_by varchar(120) NULL,
ADD COLUMN IF NOT EXISTS rejected_at timestamptz NULL,
ADD COLUMN IF NOT EXISTS automation_executed boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS automation_executed_at timestamptz NULL,
ADD COLUMN IF NOT EXISTS prompt_version VARCHAR(100),
ADD COLUMN IF NOT EXISTS model_version VARCHAR(100),
ADD COLUMN IF NOT EXISTS input_tokens INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS output_tokens INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_tokens INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS estimated_cost_usd DOUBLE PRECISION DEFAULT 0,
ADD COLUMN IF NOT EXISTS user_queue_correct BOOLEAN,
ADD COLUMN IF NOT EXISTS corrected_queue VARCHAR(100),
ADD COLUMN IF NOT EXISTS user_priority_correct BOOLEAN,
ADD COLUMN IF NOT EXISTS corrected_priority VARCHAR(50),
ADD COLUMN IF NOT EXISTS user_intent_correct BOOLEAN,
ADD COLUMN IF NOT EXISTS corrected_intent VARCHAR(100),
ADD COLUMN IF NOT EXISTS user_recommended_action_correct BOOLEAN,
ADD COLUMN IF NOT EXISTS corrected_recommended_action TEXT,
ADD COLUMN IF NOT EXISTS user_feedback_notes TEXT,
ADD COLUMN IF NOT EXISTS correction_applied_by VARCHAR(100),
ADD COLUMN IF NOT EXISTS correction_source VARCHAR(50),
ADD COLUMN IF NOT EXISTS correction_json JSONB,
ADD COLUMN IF NOT EXISTS feedback_at TIMESTAMPTZ;